VCS_FOLDER: &vcs_folder '.vcs_lite'

REPO_FOLDER: '.repo'
BLOB_FOLDER: 'blob'
SESSION_FOLDER: 'sessions'
STATE_FOLDER: 'states'

WORKSPACE_FOLDER: '.workspace'
HEADER_FILE: 'STATE_HEAD'

LOG_PREFIX: 'VCS-Lite'

INCLUDE_PATTERN:
  - '**/*'

EXCLUDE_PATTERN: 
  - *vcs_folder
