VCS_FOLDER: &vcs_folder '.vcs_lite'

REPO:
  REPO_FOLDER: '.repo'
  BLOB_FOLDER: 'blob'
  SESSION_FOLDER: 'sessions'
  STATE_FOLDER: 'states'

WORKSPACE:
  WORKSPACE_FOLDER: '.workspace'
  METADATA_FILE: 'METADATA'
  REPO_RECORD_KEY: 'repo_record'
  PATH_KEY: 'path'
  CURRENT_STATE_KEY: 'current_state'

LOG_PREFIX: 'VCS-Lite'

INCLUDE_PATTERN:
  - '**/*'

EXCLUDE_PATTERN: 
  - *vcs_folder
