VCS_FOLDER: &vcs_folder '.vcs_lite'

REPO:
  FOLDER: '.repo'
  METADATA:
    FILE: 'METADATA'
    REPO_ID_KEY: 'repo_id'

BLOB:
  FOLDER: 'blob'

SESSION:
  FOLDER: 'session'
  CONTENT:
    REVISION_KEY: 'revision'
    DETAIL_VERSION_KEY: 'detail_version'

STATE:
  FOLDER: 'state'
  CONTENT:
    FILE_KEY: 'file'
    TIMESTAMP_KEY: 'timestamp'
    SESSION_LIST_KEY: 'session_list'
    DATA_KEY: 'data'

WORKSPACE:
  FOLDER: '.workspace'
  METADATA:
    FILE: 'METADATA'
    REPO_RECORD_KEY: 'repo_record'
    PATH_KEY: 'path'
    SESSION_ID_KEY: 'session_id'
    REVISION_KEY: 'revision'

WORKSPACE_HASH:
  HASH_KEY: 'hash'
  RELATIVE_PATH_KEY: 'relative_path'
  ABSOLUTE_PATH_KEY: 'absolute_path'

LOG_PREFIX: '[VCS-Lite]'
LOG_FOLDER: 'logging'

DEFAULT_FILE_PATTERN:
  INCLUDE:
    - '**/*'
  EXCLUDE:
    - *vcs_folder
